build:
  version: "5.0"

accounts:
  message: "Welcome to ZettaBank accounts related prod APIs "
  contactDetails:
    name: "Valerie - Product Owner"
    email: "valerie@zettabank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384


spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 1234
    url: jdbc:h2:mem:accountsinfodb
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
